In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

import warnings
warnings.filterwarnings('ignore')

In [ ]:
from google.colab import files
uploaded=files.upload()

Saving Advertising.csv to Advertising (2).csv


In [ ]:
data=pd.read_csv('Advertising.csv')

In [ ]:
data

TV  Radio  Newspaper  Sales
0    230.1   37.8       69.2   22.1
1     44.5   39.3       45.1   10.4
2     17.2   45.9       69.3    9.3
3    151.5   41.3       58.5   18.5
4    180.8   10.8       58.4   12.9
..     ...    ...        ...    ...
195   38.2    3.7       13.8    7.6
196   94.2    4.9        8.1    9.7
197  177.0    9.3        6.4   12.8
198  283.6   42.0       66.2   25.5
199  232.1    8.6        8.7   13.4

[200 rows x 4 columns]

In [ ]:
data.shape

(200, 4)

In [ ]:
data.corr()

TV     Radio  Newspaper     Sales
TV         1.000000  0.054809   0.056648  0.782224
Radio      0.054809  1.000000   0.354104  0.576223
Newspaper  0.056648  0.354104   1.000000  0.228299
Sales      0.782224  0.576223   0.228299  1.000000

TV is highly affecting sales and newspaper is not affecting sales that much

In [ ]:
#X=data.iloc[:,:3], X=data.iloc[:,0:4], X=data[['TV','Radio','Newspaper']]
X=data.iloc[:,:-1]
X

TV  Radio  Newspaper
0    230.1   37.8       69.2
1     44.5   39.3       45.1
2     17.2   45.9       69.3
3    151.5   41.3       58.5
4    180.8   10.8       58.4
..     ...    ...        ...
195   38.2    3.7       13.8
196   94.2    4.9        8.1
197  177.0    9.3        6.4
198  283.6   42.0       66.2
199  232.1    8.6        8.7

[200 rows x 3 columns]

In [ ]:
y=data.iloc[:,-1]
y

0      22.1
1      10.4
2       9.3
3      18.5
4      12.9
       ... 
195     7.6
196     9.7
197    12.8
198    25.5
199    13.4
Name: Sales, Length: 200, dtype: float64

In [ ]:
X.shape

(200, 3)

In [ ]:
y.shape

(200,)

We are not getting (200,1) because it is in series not as a dataframe

In [ ]:
type(X)

pandas.core.frame.DataFrame

In [ ]:
type(y)

pandas.core.series.Series

In [ ]:
X.drop(['Newspaper'],axis=1,inplace=True)

In [ ]:
X.head()

TV  Radio
0  230.1   37.8
1   44.5   39.3
2   17.2   45.9
3  151.5   41.3
4  180.8   10.8

In [ ]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=110)

sklearn : library, model_selection : module, train_test_split : function; [test_size is user's choice]

In [ ]:
X_train.head()

TV  Radio
165  234.5    3.4
25   262.9    3.5
43   206.9    8.4
63   102.7   29.6
181  218.5    5.4

In [ ]:
X_test.head()

TV  Radio
168  215.4   23.6
197  177.0    9.3
147  243.2   49.0
124  229.5   32.3
140   73.4   17.0

In [ ]:
y_train.head()

165    11.9
25     12.0
43     12.9
63     14.0
181    12.2
Name: Sales, dtype: float64

In [ ]:
y_test.head()

168    17.1
197    12.8
147    25.4
124    19.7
140    10.9
Name: Sales, dtype: float64

In [ ]:
X_train.shape

(160, 2)

In [ ]:
X_test.shape

(40, 2)

In [ ]:
y_train.shape

(160,)

In [ ]:
y_test.shape

(40,)

In [ ]:
X_train.describe()

TV       Radio
count  160.000000  160.000000
mean   145.585000   22.281875
std     86.935101   15.097481
min      0.700000    0.000000
25%     69.000000    8.350000
50%    150.650000   20.950000
75%    218.825000   36.525000
max    296.400000   49.600000

In [ ]:
X_test.describe()

TV      Radio
count   40.000000  40.000000
mean   152.872500  27.192500
std     82.188561  13.254866
min     19.400000   4.300000
25%     75.250000  16.000000
50%    138.550000  27.700000
75%    219.400000  36.075000
max    293.600000  49.400000

In [ ]:
X_train.columns

Index(['TV', 'Radio'], dtype='object')

In [ ]:
X_test.columns

Index(['TV', 'Radio'], dtype='object')

In [ ]:
y_train.describe()

count    160.000000
mean      13.646875
std        5.145016
min        1.600000
25%       10.000000
50%       12.900000
75%       16.925000
max       27.000000
Name: Sales, dtype: float64

In [ ]:
y_test.describe()

count    40.000000
mean     15.525000
std       5.299625
min       6.600000
25%      11.525000
50%      13.750000
75%      19.475000
max      26.200000
Name: Sales, dtype: float64

In [ ]:
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()
X_train[['TV','Radio']]=scaler.fit_transform(X_train[['TV','Radio']])
X_train.head()

TV     Radio
165  1.025986 -1.254591
25   1.353692 -1.247946
43   0.707511 -0.922370
63  -0.494848  0.486247
181  0.841362 -1.121702

In [ ]:
X_test[['TV','Radio']]=scaler.fit_transform(X_test[['TV','Radio']])
X_test.head()

TV     Radio
168  0.770473 -0.274485
197  0.297303 -1.367078
147  1.113029  1.666204
124  0.944215  0.390239
140 -0.979272 -0.778759

In [ ]:
from sklearn.linear_model import LinearRegression
model=LinearRegression()
model.fit(X_train,y_train)

LinearRegression()

In [ ]:
model.intercept_

13.646875

In [ ]:
model.coef_

array([3.95940425, 2.76381841])

In [ ]:
y_pred_test = model.predict(X_test)
y_pred_test

array([15.93886121, 11.04566003, 22.65889082, 18.46395442,  7.61719419,
        5.77651784,  8.12345939, 16.95102253,  8.82293176,  9.97596351,
       16.13485265, 12.2048022 , 18.30748659, 15.6868618 ,  4.77145328,
       20.61990672, 19.97161342, 20.58203468, 23.15175158,  7.73169875,
       14.37110447,  8.01343962, 20.71245677, 15.83027029,  8.40675246,
       12.34357856, 19.1110411 ,  6.41039686, 12.72770106,  4.89593725,
       18.14165562,  8.18725431, 10.25730935, 23.55807482, 11.50119112,
        7.26941698, 12.18728352, 16.97243566, 10.1779425 , 20.26284029])

In [ ]:
y_test.tail()

29     10.5
161    13.3
105    19.2
6      11.8
111    21.8
Name: Sales, dtype: float64

In [ ]:
y_pred_train=model.predict(X_train)
y_pred_train

array([14.24170638, 15.55759151, 13.89893329, 13.03147017, 13.87798781,
       14.64690217, 17.1200731 ,  3.5756048 ,  7.61991582, 14.68638712,
        6.42658793, 21.06945121,  5.71519777,  7.08887417, 18.25413031,
       14.81301036, 17.94734165, 12.7224586 ,  8.10871296, 11.99460268,
       15.2076707 , 15.96770959, 12.57420656, 17.56000455, 15.18201234,
        8.39743607, 14.25728449, 13.30671771, 14.02238072, 18.27017982,
       15.07073151, 16.28061417, 13.5783494 , 10.62629871,  7.49027355,
       20.1945369 , 16.68304536, 18.02038378, 23.03219873, 23.14101841,
       15.03539398, 10.01663565, 14.20062416, 11.9306692 , 12.65214467,
        8.06382676, 16.75303458, 13.14722819, 12.15377001,  9.86233546,
       11.67799829, 16.16740378, 18.79991503, 15.55248867, 11.70081314,
        8.76993604, 10.38142243, 11.6206496 , 12.11852656,  7.5330208 ,
       18.23716181, 12.28110287, 18.28067886, 20.5544014 , 16.26269277,
       21.64306713, 14.61239716, 12.30586853, 11.9012382 ,  8.81

In [ ]:
y_train.tail()

89     16.7
125    10.6
15     22.4
61     24.2
128    24.7
Name: Sales, dtype: float64

In [ ]:
from sklearn.metrics import r2_score

In [ ]:
r2_train=r2_score(y_train,y_pred_train)
r2_test=r2_score(y_test,y_pred_test)
print(r2_train,r2_test)

0.8820440065485304 0.8227345476241517


In [ ]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=110)

In [ ]:
X_train.head()

TV  Radio  Newspaper
165  234.5    3.4       84.8
25   262.9    3.5       19.5
43   206.9    8.4       26.4
63   102.7   29.6        8.4
181  218.5    5.4       27.4

In [ ]:
X_test.head()

TV  Radio  Newspaper
168  215.4   23.6       57.6
197  177.0    9.3        6.4
147  243.2   49.0       44.3
124  229.5   32.3       74.2
140   73.4   17.0       12.9

In [ ]:
y_train.head()

165    11.9
25     12.0
43     12.9
63     14.0
181    12.2
Name: Sales, dtype: float64

In [ ]:
y_test.head()

168    17.1
197    12.8
147    25.4
124    19.7
140    10.9
Name: Sales, dtype: float64

In [ ]:
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()
X_train[['TV','Radio','Newspaper']]=scaler.fit_transform(X_train[['TV','Radio','Newspaper']])
X_train.head()

TV     Radio  Newspaper
165  1.025986 -1.254591   2.556583
25   1.353692 -1.247946  -0.452856
43   0.707511 -0.922370  -0.134860
63  -0.494848  0.486247  -0.964415
181  0.841362 -1.121702  -0.088774

In [ ]:
X_test[['TV','Radio','Newspaper']]=scaler.fit_transform(X_test[['TV','Radio','Newspaper']])
X_test.head()

TV     Radio  Newspaper
168  0.770473 -0.274485   1.047823
197  0.297303 -1.367078  -1.375874
147  1.113029  1.666204   0.418230
124  0.944215  0.390239   1.833631
140 -0.979272 -0.778759  -1.068178

In [ ]:
from sklearn.linear_model import LinearRegression
model=LinearRegression()
model.fit(X_train,y_train)

LinearRegression()

In [ ]:
model.intercept_

13.646875

In [ ]:
model.coef_

array([ 3.95814068,  2.79400747, -0.09238047])

In [ ]:
y_pred_test = model.predict(X_test)
y_pred_test

array([15.83280285, 11.13111745, 22.66914931, 18.30515061,  7.69360036,
        5.8877088 ,  8.02273104, 16.87274149,  8.81032926, 10.06298723,
       16.13464824, 12.08822761, 18.36072753, 15.71624959,  4.80528657,
       20.76610631, 20.08148629, 20.52524803, 23.04946418,  7.74138476,
       14.20266172,  8.07761235, 20.67900525, 15.9086537 ,  8.40502825,
       12.44009225, 19.05281215,  6.50264376, 12.89293758,  4.89720726,
       18.05227444,  8.18942364, 10.27092496, 23.43354242, 11.44504057,
        7.22155092, 12.14768172, 16.91405207, 10.24468572, 20.34002178])

In [ ]:
y_pred_train = model.predict(X_train)
y_pred_train

array([13.9663567 , 15.56004176, 13.88265227, 13.13586787, 13.85126252,
       14.68473857, 17.23033775,  3.54950832,  7.57606671, 14.67538867,
        6.32940174, 20.91347578,  5.70960309,  7.071668  , 18.08273271,
       14.89833875, 18.04613236, 12.3918165 ,  8.05681483, 12.06506241,
       15.23571754, 15.94967015, 12.63551063, 17.5673522 , 15.13518027,
        8.35971906, 14.17728819, 13.31382167, 14.06913954, 18.21963726,
       15.09886746, 16.40657987, 13.59576452, 10.69178118,  7.54021261,
       20.26306594, 16.67670201, 18.01929657, 22.95224526, 23.28598106,
       15.02614648,  9.96158785, 14.21960623, 11.99658089, 12.70028136,
        8.09256436, 16.79621757, 12.9999025 , 12.12222388,  9.82090687,
       11.55788051, 16.08547184, 18.88706695, 15.45365108, 11.48988898,
        8.71905616, 10.44381605, 11.44029693, 11.99758631,  7.58521202,
       18.38593381, 12.14203658, 18.22922491, 20.5759225 , 16.33768664,
       21.66126228, 14.5423076 , 12.33086492, 11.94081259,  8.76

In [ ]:
from sklearn.metrics import r2_score

In [ ]:
r2_train=r2_score(y_train,y_pred_train)
r2_test=r2_score(y_test,y_pred_test)
print(r2_train,r2_test)

0.8823337069164685 0.8221608439158414


In [ ]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.3,random_state=110)

In [ ]:
X_train.head()

TV  Radio
97   184.9   21.0
178  276.7    2.3
96   197.6    3.5
102  280.2   10.1
156   93.9   43.5

In [ ]:
X_test.head()

TV  Radio
168  215.4   23.6
197  177.0    9.3
147  243.2   49.0
124  229.5   32.3
140   73.4   17.0

In [ ]:
y_train.head()

97     15.5
178    11.8
96     11.7
102    14.8
156    15.3
Name: Sales, dtype: float64

In [ ]:
y_test.head()

168    17.1
197    12.8
147    25.4
124    19.7
140    10.9
Name: Sales, dtype: float64

In [ ]:
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()
X_train[['TV','Radio']]=scaler.fit_transform(X_train[['TV','Radio']])
X_train.head()

TV     Radio
97   0.454808 -0.146573
178  1.502634 -1.385208
96   0.599769 -1.305723
102  1.542583 -0.868558
156 -0.583886  1.343762

In [ ]:
X_test[['TV','Radio']]=scaler.fit_transform(X_test[['TV','Radio']])
X_test.head()

TV     Radio
168  0.789921  0.015350
197  0.313873 -0.997754
147  1.134559  1.814850
124  0.964720  0.631714
140 -0.970463 -0.452237

In [ ]:
from sklearn.linear_model import LinearRegression
model=LinearRegression()
model.fit(X_train,y_train)

LinearRegression()

In [ ]:
model.intercept_

13.774285714285716

In [ ]:
model.coef_

array([4.12433713, 2.75188733])

In [ ]:
y_pred_test=model.predict(X_test)
y_pred_test

array([17.07442701, 12.32309683, 23.44785497, 19.49152092,  8.52726288,
        6.80108861,  9.28436796, 18.02715828,  9.86198811, 10.72263479,
       17.02166902, 13.66957797, 19.46452444, 16.99209638,  5.57129727,
       21.87211216, 20.73435035, 21.2607936 , 24.14876457,  8.89224638,
       15.08108037,  8.70807719, 21.95329826, 16.82627882,  9.26778228,
       13.17752929, 19.80350259,  7.42587395, 13.09275231,  5.97044721,
       19.1221442 ,  8.86915936, 11.36520146, 24.5482449 , 12.12349041,
        8.1891382 , 12.82143449, 17.55699705, 10.79469228, 21.22658389,
       14.11278206, 15.58436185, 13.67640969, 12.48187818, 13.68462977,
       14.42060649, 17.11662081,  2.2077807 ,  6.7222466 , 14.59249276,
        5.23479694, 21.40453493,  4.58535921,  6.1406108 , 18.26545811,
       14.4788039 , 17.98439025, 12.06218196,  7.16162383, 11.42703301])

In [ ]:
y_pred_train=model.predict(X_train)
y_pred_train

array([15.24671346, 16.15971717, 12.65472981, 17.74624534, 15.06402382,
        8.18016492, 14.26813319, 13.39770114, 14.00525564, 18.31967282,
       14.92644357, 16.25088099, 13.69703413, 10.4108046 ,  7.30098378,
       20.33099627, 16.80512925, 18.0150612 , 23.1799127 , 23.26287322,
       15.05878336,  9.94094455, 14.04586029, 11.91524155, 12.62600825,
        7.94405484, 16.68766094, 13.19447446, 11.97290016,  9.84514915,
       11.48752776, 16.16200741, 18.9030105 , 15.72770825, 11.47561913,
        8.58065443, 10.32237521, 11.51940886, 11.8907517 ,  7.47489264,
       18.22245618, 12.03743626, 18.46243658, 20.60318746, 16.33658241,
       21.67911119, 14.75070775, 12.33309593, 11.93630528,  8.74179181,
       12.14863628, 19.64101411, 20.43680961, 12.26834405, 19.14640409,
        9.66442007, 10.17229623, 11.17793579, 20.18015603,  9.66562552,
       16.6801681 ,  8.04224852, 17.24458022, 16.26381746, 19.42086028,
       17.37459776, 18.54494028, 14.25140275,  6.49002499, 20.86

In [ ]:
from sklearn.metrics import r2_score

In [ ]:
r2_train=r2_score(y_train,y_pred_train)
r2_test=r2_score(y_test,y_pred_test)
print(r2_train,r2_test)

0.884019695114733 0.892090472519704


In [ ]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)

In [ ]:
X_train.head()

TV  Radio
79   116.0    7.7
197  177.0    9.3
38    43.1   26.7
24    62.3   12.6
122  224.0    2.4

In [ ]:
X_test.head()

TV  Radio
95   163.3   31.6
15   195.4   47.7
30   292.9   28.3
158   11.7   36.9
128  220.3   49.0

In [ ]:
y_train.head()

79     11.0
197    12.8
38     10.1
24      9.7
122    11.6
Name: Sales, dtype: float64

In [ ]:
y_test.head()

95     16.9
15     22.4
30     21.4
158     7.3
128    24.7
Name: Sales, dtype: float64

In [ ]:
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()
X_train[['TV','Radio']]=scaler.fit_transform(X_train[['TV','Radio']])
X_train.head()

TV     Radio
79  -0.404248 -1.028237
197  0.320608 -0.919828
38  -1.270511  0.259124
24  -1.042359 -0.696233
122  0.879103 -1.387343

In [ ]:
X_test[['TV','Radio']]=scaler.fit_transform(X_test[['TV','Radio']])
X_test.head()

TV     Radio
95   0.311692  0.454891
15   0.666931  1.534690
30   1.745928  0.233565
158 -1.366011  0.810352
128  0.942490  1.621879

In [ ]:
from sklearn.linear_model import LinearRegression
model=LinearRegression()
model.fit(X_train,y_train)

LinearRegression()

In [ ]:
model.intercept_

14.100000000000001

In [ ]:
model.coef_

array([3.76409388, 2.81403482])

In [ ]:
y_pred_test=model.predict(X_test)
y_pred_test

array([16.55331555, 20.92906167, 21.32909942, 11.23856742, 22.21164508,
       13.52095802, 21.10331397,  8.05905604, 13.69292216, 15.32738944,
        9.74194441,  7.20380092, 14.19695821,  9.6550082 ,  9.99429819,
       12.34890848,  9.39443593, 16.41563252, 10.75492201, 18.86621256,
       19.44304699, 13.5188421 , 12.97580722, 21.12715899,  8.41643294,
        6.39301996, 20.79599038, 12.32624953,  9.64640097,  9.27039817,
       12.60051349, 10.53856769, 21.3957024 , 12.7385587 , 18.10315034,
       20.182918  , 14.6693702 , 20.64254616, 11.44340126,  5.23447431])

In [ ]:
y_pred_train=model.predict(X_train)
y_pred_train

array([ 9.68487622, 12.71837026, 10.04686103,  8.217236  , 13.50499633,
        5.44234526,  9.2367496 , 14.17368175,  8.79363904, 11.68437447,
       15.44923645, 11.91423888, 12.74102071, 10.7940926 ,  6.59803133,
        9.90290093,  9.55265611, 24.05126962,  7.73734199, 12.53390315,
       17.7655845 , 15.30253084, 11.39569095, 10.78520982, 16.81250842,
        6.94666054, 21.44196794,  6.1717484 ,  9.9695358 , 11.6093231 ,
        9.34938251,  6.61546507, 14.90614483, 17.31345133, 15.68622487,
       16.33105299, 15.00648045, 19.6688112 , 13.79569885, 21.08444189,
       12.54920949, 13.85203268,  8.92798986, 17.04798425,  8.46444851,
       15.17804086, 13.6873588 , 23.31746523, 12.63144775, 22.85725275,
        6.65027834, 18.44174851, 23.20694566, 18.72143754, 17.20743603,
       16.51183667, 12.42725029, 11.85401889, 16.95166387, 14.45824701,
       13.1743387 ,  7.6618471 , 19.22099902,  9.66590382, 19.58081299,
       10.15299342,  7.09066615, 16.68708051, 13.82329378, 15.15

In [ ]:
from sklearn.metrics import r2_score

In [ ]:
r2_train=r2_score(y_train,y_pred_train)
r2_test=r2_score(y_test,y_pred_test)
print(r2_train,r2_test)

0.8955982149747163 0.886950913178407


In [ ]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.3,random_state=42)

In [ ]:
X_train.head()

TV  Radio
169  284.3   10.6
97   184.9   21.0
31   112.9   17.4
12    23.8   35.1
35   290.7    4.1

In [ ]:
X_test.head()

TV  Radio
95   163.3   31.6
15   195.4   47.7
30   292.9   28.3
158   11.7   36.9
128  220.3   49.0

In [ ]:
y_train.head()

169    15.0
97     15.5
31     11.9
12      9.2
35     12.8
Name: Sales, dtype: float64

In [ ]:
y_test.head()

95     16.9
15     22.4
30     21.4
158     7.3
128    24.7
Name: Sales, dtype: float64

In [ ]:
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()
X_train[['TV','Radio']]=scaler.fit_transform(X_train[['TV','Radio']])
X_train.head()

TV     Radio
169  1.530039 -0.886293
97   0.341039 -0.173144
31  -0.520209 -0.420003
12  -1.586003  0.793721
35   1.606594 -1.332011

In [ ]:
X_test[['TV','Radio']]=scaler.fit_transform(X_test[['TV','Radio']])
X_test.head()

TV     Radio
95   0.440731  0.584347
15   0.812381  1.636107
30   1.941224  0.368769
158 -1.314475  0.930578
128  1.100670  1.721031

In [ ]:
from sklearn.linear_model import LinearRegression
model=LinearRegression()
model.fit(X_train,y_train)

LinearRegression()

In [ ]:
model.intercept_

14.497142857142858

In [ ]:
model.coef_

array([3.68485252, 2.9546419 ])

In [ ]:
y_pred_test=model.predict(X_test)
y_pred_test

array([17.84770851, 22.32475582, 22.73984677, 12.40302331, 23.63798064,
       14.74111034, 22.50427461,  9.15367877, 14.92600035, 16.59467504,
       10.87363776,  8.27938801, 15.44221978, 10.78312938, 11.13833525,
       13.5482786 , 10.51675815, 17.70900076, 11.91229399, 20.21764986,
       20.8070953 , 14.73849926, 14.18131156, 22.53074955,  9.52033233,
        7.4500359 , 22.18977226, 13.52321265, 10.77933696, 10.38997195,
       13.80740835, 11.69065452, 22.80220427, 13.93738482, 19.43991724,
       21.56429521, 15.91395146, 22.03653188, 12.61896896,  6.26359728,
       11.21665512, 14.12791079, 11.77386138,  9.87144769, 14.80124384,
        7.1254244 , 10.8818062 , 15.67887392, 10.34426576, 13.34467867,
       17.1509647 , 13.33637377, 14.5912382 , 12.6226724 ,  8.19539286,
       11.40230229, 11.19427887, 25.30556298,  9.49737469, 13.88726551])

In [ ]:
y_pred_train=model.predict(X_train)
y_pred_train

array([17.51643183, 15.2422407 , 11.33929011, 10.99811715, 16.48159017,
        6.93440865, 21.39090809,  6.11339242,  9.74997496, 11.86761848,
        9.20799892,  6.37262183, 14.80895506, 17.4063397 , 15.85429073,
       16.24990933, 15.07261838, 19.8819103 , 13.51162734, 21.19013119,
       12.89534767, 13.9232009 ,  8.79715282, 17.07558394,  8.35359935,
       15.08130811, 13.86832995, 23.47599359, 12.90576572, 23.00629412,
        6.64086843, 18.547643  , 23.25673338, 18.59667832, 17.16356313,
       16.64876011, 12.37055022, 12.0175313 , 16.80410686, 14.49558045,
       12.99494578,  7.42584551, 19.28318391,  9.40662217, 19.54506826,
       10.07642342,  6.92624383, 16.52571818, 13.70213726, 14.89961366,
       11.24457485, 20.63831263, 23.84739538, 18.43151438, 17.8131536 ,
       15.27369657, 17.28768189,  9.15092452, 17.50015453, 19.29467879,
       16.28138966,  3.49607297,  5.36856008, 15.78982791, 15.13467606,
       16.3245151 , 18.33995278, 23.48490949, 14.23805234, 20.52

In [ ]:
from sklearn.metrics import r2_score

In [ ]:
r2_train=r2_score(y_train,y_pred_train)
r2_test=r2_score(y_test,y_pred_test)
print(r2_train,r2_test)

0.9048377867980043 0.7760464969781223


In [ ]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=1)

In [ ]:
X_train.head()

TV  Radio
108   13.1    0.4
107   90.4    0.3
189   18.7   12.1
14   204.1   32.9
56     7.3   28.1

In [ ]:
X_test.head()

TV  Radio
58   210.8   49.6
40   202.5   22.3
34    95.7    1.4
102  280.2   10.1
184  253.8   21.3

In [ ]:
y_train.head()

108     5.3
107     8.7
189     6.7
14     19.0
56      5.5
Name: Sales, dtype: float64

In [ ]:
y_test.head()

58     23.8
40     16.6
34      9.5
102    14.8
184    17.6
Name: Sales, dtype: float64

In [ ]:
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()
X_train[['TV','Radio']]=scaler.fit_transform(X_train[['TV','Radio']])
X_train.head()

TV     Radio
108 -1.478614 -1.507409
107 -0.593912 -1.513991
189 -1.414522 -0.737311
14   0.707390  0.631752
56  -1.544995  0.315814

In [ ]:
X_test[['TV','Radio']]=scaler.fit_transform(X_test[['TV','Radio']])
X_test.head()

TV     Radio
58   0.593748  2.012031
40   0.483642 -0.061719
34  -0.933156 -1.649315
102  1.514402 -0.988449
184  1.164182 -0.137680

In [ ]:
from sklearn.linear_model import LinearRegression
model=LinearRegression()
model.fit(X_train,y_train)

LinearRegression()

In [ ]:
model.intercept_

13.811250000000001

In [ ]:
model.coef_

array([4.09521919, 2.73481621])

In [ ]:
y_pred_train=model.predict(X_train)
y_pred_train

array([ 3.63351431,  7.23856273,  6.00206226, 18.4358909 ,  8.34784861,
       14.15361779, 15.03705145, 20.42011452, 20.67415323, 19.51838436,
       24.1400219 , 14.94543399,  6.73689661, 19.82227294, 18.99631047,
       12.50924793, 14.16063969,  6.09933595, 15.37409216,  9.62509241,
       12.04590856, 12.08659685,  8.58280736, 21.69471984, 23.26498354,
       12.15760185,  6.70648703, 17.76318636, 16.44047611,  8.85207924,
       20.44444477, 20.69453435, 24.1675995 , 10.13813373, 10.55473213,
       16.47959577, 10.38124872,  6.67238633, 21.27742914, 14.3944168 ,
       15.54783357, 10.12418454, 14.9249617 , 13.87840504,  8.43026839,
        8.88538702, 10.13095618,  8.23739973, 17.07055391, 15.20459399,
       16.79060686, 23.34139622, 13.40850473,  9.8638902 , 18.12259995,
       14.8504952 ,  5.40397214, 12.91756109, 11.98283619, 12.118465  ,
       11.60590183, 14.99248027,  4.55800608, 16.40317363, 12.01597713,
       17.78752607, 15.31491387, 18.60600741, 11.54675192, 13.95

In [ ]:
y_pred_test=model.predict(X_test)
y_pred_test

array([21.74531526, 15.62307856,  5.47919695, 17.30982999, 18.2023007 ,
       24.12147336, 15.42545912, 12.05516828,  7.14861125, 16.59395688,
       13.26782439,  8.0073875 , 16.63902448, 15.88437866, 13.95974649,
       14.48379919, 10.96655448, 16.63381605,  9.48194591, 17.56429197,
        7.43800751, 11.27595734,  6.69182953,  8.73235449,  9.7374705 ,
       13.98455972,  7.8774521 , 19.13556367, 17.77610739, 16.50241623,
       21.64352338, 13.43523336, 15.51757844, 10.85608211, 19.75782953,
       14.39686445, 12.77787953,  8.20329443, 20.88715313,  5.2296837 ])

In [ ]:
from sklearn.metrics import r2_score

In [ ]:
r2_train=r2_score(y_train,y_pred_train)
r2_test=r2_score(y_test,y_pred_test)
print(r2_train,r2_test)

0.8958528468776601 0.8065099347059563


In [ ]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.3,random_state=1)

In [ ]:
X_train.head()

TV  Radio
116  139.2   14.3
67   139.3   14.5
78     5.4   29.9
42   293.6   27.7
17   281.4   39.6

In [ ]:
X_test.head()

TV  Radio
58   210.8   49.6
40   202.5   22.3
34    95.7    1.4
102  280.2   10.1
184  253.8   21.3

In [ ]:
y_train.head()

116    12.2
67     13.4
78      5.3
42     20.7
17     24.4
Name: Sales, dtype: float64

In [ ]:
y_test.head()

58     23.8
40     16.6
34      9.5
102    14.8
184    17.6
Name: Sales, dtype: float64

In [ ]:
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()
X_train[['TV','Radio']]=scaler.fit_transform(X_train[['TV','Radio']])
X_train.head()

TV     Radio
116 -0.040635 -0.585621
67  -0.039480 -0.572468
78  -1.585867  0.440284
42   1.742502  0.295605
17   1.601607  1.078187

In [ ]:
X_test[['TV','Radio']]=scaler.fit_transform(X_test[['TV','Radio']])
X_test.head()

TV     Radio
58   0.650486  1.893005
40   0.549886 -0.079603
34  -0.744582 -1.589767
102  1.491648 -0.961134
184  1.171668 -0.151859

In [ ]:
from sklearn.linear_model import LinearRegression
model=LinearRegression()
model.fit(X_train,y_train)

LinearRegression()

In [ ]:
model.intercept_

13.79142857142857

In [ ]:
model.coef_

array([4.06756287, 2.70136813])

In [ ]:
y_pred_test=model.predict(X_test)
y_pred_train

array([ 3.63351431,  7.23856273,  6.00206226, 18.4358909 ,  8.34784861,
       14.15361779, 15.03705145, 20.42011452, 20.67415323, 19.51838436,
       24.1400219 , 14.94543399,  6.73689661, 19.82227294, 18.99631047,
       12.50924793, 14.16063969,  6.09933595, 15.37409216,  9.62509241,
       12.04590856, 12.08659685,  8.58280736, 21.69471984, 23.26498354,
       12.15760185,  6.70648703, 17.76318636, 16.44047611,  8.85207924,
       20.44444477, 20.69453435, 24.1675995 , 10.13813373, 10.55473213,
       16.47959577, 10.38124872,  6.67238633, 21.27742914, 14.3944168 ,
       15.54783357, 10.12418454, 14.9249617 , 13.87840504,  8.43026839,
        8.88538702, 10.13095618,  8.23739973, 17.07055391, 15.20459399,
       16.79060686, 23.34139622, 13.40850473,  9.8638902 , 18.12259995,
       14.8504952 ,  5.40397214, 12.91756109, 11.98283619, 12.118465  ,
       11.60590183, 14.99248027,  4.55800608, 16.40317363, 12.01597713,
       17.78752607, 15.31491387, 18.60600741, 11.54675192, 13.95

In [ ]:
y_pred_train=model.predict(X_train)
y_pred_train

array([12.04416442, 12.08439207,  8.53018379, 21.67770458, 23.21864341,
       12.06056182,  6.73220575, 17.68567596, 16.44448799,  8.81469806,
       20.42157578, 20.63301553, 24.11390335, 10.06968294, 10.48528663,
       16.47044062, 10.31831619,  6.69581905, 21.23517289, 14.36344381,
       15.53519899, 10.14406994, 14.95786947, 13.91365009,  8.43004566,
        8.89502616, 10.10832991,  8.19145418, 17.04036178, 15.18732022,
       16.72388483, 23.28362995, 13.35045769,  9.89092148, 18.06440106,
       14.84705975,  5.4165396 , 12.93158769, 11.90915131, 12.136767  ,
       11.52197889, 15.02277862,  4.57474337, 16.38639033, 11.92690256,
       17.753702  , 15.30921069, 18.62014373, 11.49279597, 13.95418729,
       20.48902718,  5.21811218, 13.68835827,  7.85822893, 21.08413553,
       13.60309202, 11.64279438, 10.03260819,  8.93721297, 16.95959694,
       17.35954953, 19.14263345, 23.09409195, 14.28352179,  8.89101665,
       15.3775685 , 10.78302852,  9.89297183, 11.08176264,  7.10

In [ ]:
from sklearn.metrics import r2_score

In [ ]:
r2_train=r2_score(y_train,y_pred_train)
r2_test=r2_score(y_test,y_pred_test)
print(r2_train,r2_test)

0.8849581188519494 0.9001021389962338
